OM-229 Fix broken datetime string in mpay endpoints
openimis/openimis-be-msystems_py pull request #27
Opened 2024-07-22 13:50 UTC by malinowskikam

[https://openimis.atlassian.net/browse/OM-229](https://openimis.atlassian.net/browse/OM-229)

2024-07-23 07:25 UTC, dborowiecki requested changes

2024-07-23 07:25 UTC, dborowiecki commented on scripts/json_escape_file.py
I'm not sure what is the purpose of this file and o don't see execution in the code. Can you provide more context in comments or code?

2024-07-23 12:07 UTC, malinowskikam commented on scripts/json_escape_file.py
This script is useful for testing the server setup, and i find myself re-writing this every time i need to deploy it.
Mainly used for json escaping X509 certificates, so those files will be accurete byte for byte.

2024-07-23 12:43 UTC, malinowskikam commented on scripts/json_escape_file.py
this will also allow implementers to input X509 certificates in correct format into config

2024-07-29 08:06 UTC, dborowiecki approved these changes

2024-07-29 08:07 UTC, merged